-- Add board member roles to UserRole enum
ALTER TYPE "UserRole" ADD VALUE IF NOT EXISTS 'BOARD_PRESIDENT';
ALTER TYPE "UserRole" ADD VALUE IF NOT EXISTS 'BOARD_VP';
ALTER TYPE "UserRole" ADD VALUE IF NOT EXISTS 'BOARD_TREASURER';
ALTER TYPE "UserRole" ADD VALUE IF NOT EXISTS 'BOARD_SECRETARY';
ALTER TYPE "UserRole" ADD VALUE IF NOT EXISTS 'BOARD_MEMBER';
