"use client";

import { useState } from "react";
import { motion, AnimatePresence } from "framer-motion";
import { X, Sparkles, MapPin, Search } from "lucide-react";

interface DiscoverLeadsModalProps {
  isOpen: boolean;
  onClose: () => void;
  onDiscover: (params: DiscoverParams) => Promise<void>;
  isDiscovering: boolean;
}

interface DiscoverParams {
  location: string;
  radius: number;
  types: string[];
  keyword?: string;
  hasWebsite?: boolean;
  minRating?: number;
  minReviews?: number;
  analyzeWithAI: boolean;
  autoGenerateDrafts: boolean;
}

const BUSINESS_TYPES = [
  { id: "nonprofit", label: "Nonprofit / Charity" },
  { id: "restaurant", label: "Restaurant / Food Service" },
  { id: "retail", label: "Retail / Shopping" },
  { id: "professional", label: "Professional Services (law, accounting, etc.)" },
  { id: "healthcare", label: "Healthcare / Medical" },
  { id: "education", label: "Education" },
  { id: "arts", label: "Arts / Entertainment" },
];

const RADIUS_OPTIONS = [
  { value: 8047, label: "5 miles" },
  { value: 16093, label: "10 miles" },
  { value: 32187, label: "20 miles" },
  { value: 49889, label: "31 miles (max)" },
];

export function DiscoverLeadsModal({
  isOpen,
  onClose,
  onDiscover,
  isDiscovering,
}: DiscoverLeadsModalProps) {
  const [location, setLocation] = useState("Louisville, KY");
  const [radius, setRadius] = useState(16093); // 10 miles
  const [selectedTypes, setSelectedTypes] = useState<string[]>(["nonprofit"]);
  const [keyword, setKeyword] = useState("");
  const [websiteFilter, setWebsiteFilter] = useState<"all" | "none" | "poor">("all");
  const [minRating, setMinRating] = useState(4.0);
  const [minReviews, setMinReviews] = useState(10);
  const [analyzeWithAI, setAnalyzeWithAI] = useState(true);
  const [autoGenerateDrafts, setAutoGenerateDrafts] = useState(false);
  const [skipDuplicates, setSkipDuplicates] = useState(true);

  const handleTypeToggle = (typeId: string) => {
    setSelectedTypes((prev) =>
      prev.includes(typeId)
        ? prev.filter((t) => t !== typeId)
        : [...prev, typeId]
    );
  };

  const handleDiscover = async () => {
    if (selectedTypes.length === 0) {
      alert("Please select at least one business type");
      return;
    }

    await onDiscover({
      location,
      radius,
      types: selectedTypes,
      keyword: keyword.trim() || undefined,
      hasWebsite:
        websiteFilter === "all"
          ? undefined
          : websiteFilter === "none"
          ? false
          : undefined, // "poor" would need additional logic
      minRating: minRating > 0 ? minRating : undefined,
      minReviews: minReviews > 0 ? minReviews : undefined,
      analyzeWithAI,
      autoGenerateDrafts,
    });
  };

  if (!isOpen) return null;

  return (
    <AnimatePresence>
      <div className="fixed inset-0 z-50 flex items-center justify-center p-4">
        {/* Backdrop */}
        <motion.div
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          exit={{ opacity: 0 }}
          onClick={onClose}
          className="absolute inset-0 bg-black/60 backdrop-blur-sm"
        />

        {/* Modal */}
        <motion.div
          initial={{ opacity: 0, scale: 0.95, y: 20 }}
          animate={{ opacity: 1, scale: 1, y: 0 }}
          exit={{ opacity: 0, scale: 0.95, y: 20 }}
          className="relative w-full max-w-2xl max-h-[90vh] overflow-y-auto rounded-2xl border-2 border-gray-700 bg-[#0a0e1a] shadow-2xl"
        >
          {/* Header */}
          <div className="sticky top-0 z-10 flex items-center justify-between border-b border-gray-800 bg-[#0a0e1a] px-6 py-4">
            <div className="flex items-center gap-3">
              <Sparkles className="w-5 h-5 text-purple-400" />
              <h2 className="text-xl font-heading font-bold text-white">
                Discover New Leads
              </h2>
            </div>
            <button
              onClick={onClose}
              className="p-2 rounded-lg hover:bg-gray-800 transition"
            >
              <X className="w-5 h-5 text-gray-400" />
            </button>
          </div>

          {/* Content */}
          <div className="p-6 space-y-6">
            {/* Location */}
            <div>
              <label className="block text-sm font-medium text-white mb-2">
                Location
              </label>
              <div className="flex gap-2">
                <div className="flex-1 relative">
                  <MapPin className="absolute left-3 top-1/2 -translate-y-1/2 w-5 h-5 text-gray-400" />
                  <input
                    type="text"
                    value={location}
                    onChange={(e) => setLocation(e.target.value)}
                    placeholder="Louisville, KY"
                    className="w-full pl-10 pr-4 py-2 rounded-lg border border-gray-700 bg-gray-900 text-white placeholder-gray-500 focus:outline-none focus:ring-2 focus:ring-purple-500"
                  />
                </div>
                <button
                  type="button"
                  onClick={() => {
                    if (navigator.geolocation) {
                      navigator.geolocation.getCurrentPosition(
                        (position) => {
                          // You could reverse geocode here, but for now just enable location
                          alert("Location permission granted. Please enter your city/state manually.");
                        },
                        () => {
                          alert("Could not get your location. Please enter manually.");
                        }
                      );
                    }
                  }}
                  className="px-4 py-2 rounded-lg border border-gray-700 bg-gray-800 text-gray-300 hover:bg-gray-700 transition text-sm"
                >
                  Use My Location
                </button>
              </div>
            </div>

            {/* Radius */}
            <div>
              <label className="block text-sm font-medium text-white mb-2">
                Radius
              </label>
              <div className="flex gap-2">
                {RADIUS_OPTIONS.map((option) => (
                  <button
                    key={option.value}
                    type="button"
                    onClick={() => setRadius(option.value)}
                    className={`flex-1 px-4 py-2 rounded-lg border transition ${
                      radius === option.value
                        ? "border-purple-500 bg-purple-500/20 text-purple-300"
                        : "border-gray-700 bg-gray-800 text-gray-300 hover:bg-gray-700"
                    }`}
                  >
                    {option.label}
                  </button>
                ))}
              </div>
            </div>

            {/* Business Type */}
            <div>
              <label className="block text-sm font-medium text-white mb-2">
                Business Type
              </label>
              <div className="space-y-2">
                {BUSINESS_TYPES.map((type) => (
                  <label
                    key={type.id}
                    className="flex items-center gap-3 p-3 rounded-lg border border-gray-700 bg-gray-900 hover:bg-gray-800 cursor-pointer transition"
                  >
                    <input
                      type="checkbox"
                      checked={selectedTypes.includes(type.id)}
                      onChange={() => handleTypeToggle(type.id)}
                      className="w-4 h-4 rounded border-gray-600 bg-gray-800 text-purple-500 focus:ring-purple-500"
                    />
                    <span className="text-white">{type.label}</span>
                  </label>
                ))}
              </div>
            </div>

            {/* Keywords */}
            <div>
              <label className="block text-sm font-medium text-white mb-2">
                Keywords (Optional)
              </label>
              <input
                type="text"
                value={keyword}
                onChange={(e) => setKeyword(e.target.value)}
                placeholder='e.g., "charity OR community OR foundation"'
                className="w-full px-4 py-2 rounded-lg border border-gray-700 bg-gray-900 text-white placeholder-gray-500 focus:outline-none focus:ring-2 focus:ring-purple-500"
              />
              <p className="mt-1 text-xs text-gray-400">
                Examples: "mental health", "recovery center", "food bank"
              </p>
            </div>

            {/* Website Filter */}
            <div>
              <label className="block text-sm font-medium text-white mb-2">
                Website Filter
              </label>
              <div className="space-y-2">
                {[
                  { value: "all", label: "All businesses (find anyone)" },
                  { value: "none", label: "No website only (🎯 prime targets)" },
                  {
                    value: "poor",
                    label: "Has website but poor quality (modernization opps)",
                  },
                ].map((option) => (
                  <label
                    key={option.value}
                    className="flex items-center gap-3 p-3 rounded-lg border border-gray-700 bg-gray-900 hover:bg-gray-800 cursor-pointer transition"
                  >
                    <input
                      type="radio"
                      name="websiteFilter"
                      value={option.value}
                      checked={websiteFilter === option.value}
                      onChange={(e) =>
                        setWebsiteFilter(e.target.value as any)
                      }
                      className="w-4 h-4 border-gray-600 bg-gray-800 text-purple-500 focus:ring-purple-500"
                    />
                    <span className="text-white">{option.label}</span>
                  </label>
                ))}
              </div>
            </div>

            {/* Quality Filters */}
            <div className="grid grid-cols-2 gap-4">
              <div>
                <label className="block text-sm font-medium text-white mb-2">
                  Minimum Google Rating
                </label>
                <select
                  value={minRating}
                  onChange={(e) => setMinRating(parseFloat(e.target.value))}
                  className="w-full px-4 py-2 rounded-lg border border-gray-700 bg-gray-900 text-white focus:outline-none focus:ring-2 focus:ring-purple-500"
                >
                  <option value={0}>Any rating</option>
                  <option value={3.0}>3.0 stars</option>
                  <option value={3.5}>3.5 stars</option>
                  <option value={4.0}>4.0 stars</option>
                  <option value={4.5}>4.5 stars</option>
                </select>
              </div>
              <div>
                <label className="block text-sm font-medium text-white mb-2">
                  Minimum Review Count
                </label>
                <select
                  value={minReviews}
                  onChange={(e) => setMinReviews(parseInt(e.target.value))}
                  className="w-full px-4 py-2 rounded-lg border border-gray-700 bg-gray-900 text-white focus:outline-none focus:ring-2 focus:ring-purple-500"
                >
                  <option value={0}>Any reviews</option>
                  <option value={5}>5 reviews</option>
                  <option value={10}>10 reviews</option>
                  <option value={25}>25 reviews</option>
                  <option value={50}>50 reviews</option>
                  <option value={100}>100 reviews</option>
                </select>
              </div>
            </div>

            {/* Advanced Options */}
            <div>
              <label className="block text-sm font-medium text-white mb-2">
                Advanced Options
              </label>
              <div className="space-y-2">
                <label className="flex items-center gap-3 p-3 rounded-lg border border-gray-700 bg-gray-900 hover:bg-gray-800 cursor-pointer transition">
                  <input
                    type="checkbox"
                    checked={skipDuplicates}
                    onChange={(e) => setSkipDuplicates(e.target.checked)}
                    className="w-4 h-4 rounded border-gray-600 bg-gray-800 text-purple-500 focus:ring-purple-500"
                  />
                  <span className="text-white">
                    Skip organizations already in database
                  </span>
                </label>
                <label className="flex items-center gap-3 p-3 rounded-lg border border-gray-700 bg-gray-900 hover:bg-gray-800 cursor-pointer transition">
                  <input
                    type="checkbox"
                    checked={analyzeWithAI}
                    onChange={(e) => setAnalyzeWithAI(e.target.checked)}
                    className="w-4 h-4 rounded border-gray-600 bg-gray-800 text-purple-500 focus:ring-purple-500"
                  />
                  <span className="text-white">
                    Analyze with AI ($0.05 per lead)
                  </span>
                </label>
                <label className="flex items-center gap-3 p-3 rounded-lg border border-gray-700 bg-gray-900 hover:bg-gray-800 cursor-pointer transition">
                  <input
                    type="checkbox"
                    checked={autoGenerateDrafts}
                    onChange={(e) => setAutoGenerateDrafts(e.target.checked)}
                    className="w-4 h-4 rounded border-gray-600 bg-gray-800 text-purple-500 focus:ring-purple-500"
                  />
                  <span className="text-white">Auto-generate email drafts</span>
                </label>
              </div>
            </div>

            {/* Estimated Results */}
            <div className="p-4 rounded-lg border border-purple-500/30 bg-purple-500/10">
              <h4 className="text-sm font-semibold text-purple-300 mb-2">
                📊 Estimated Results
              </h4>
              <ul className="text-sm text-gray-300 space-y-1">
                <li>• Expected leads to find: 15-30</li>
                <li>
                  • AI analysis cost: $
                  {analyzeWithAI
                    ? ((15 + 30) / 2 * 0.05).toFixed(2)
                    : "0.00"}
                  {" - $"}
                  {analyzeWithAI ? (30 * 0.05).toFixed(2) : "0.00"}
                </li>
                <li>• Estimated time: 2-3 minutes</li>
              </ul>
            </div>
          </div>

          {/* Footer */}
          <div className="sticky bottom-0 flex items-center justify-end gap-3 border-t border-gray-800 bg-[#0a0e1a] px-6 py-4">
            <button
              type="button"
              onClick={onClose}
              disabled={isDiscovering}
              className="px-6 py-2 rounded-lg border border-gray-700 bg-gray-800 text-gray-300 hover:bg-gray-700 transition disabled:opacity-50"
            >
              Cancel
            </button>
            <button
              type="button"
              onClick={handleDiscover}
              disabled={isDiscovering || selectedTypes.length === 0}
              className="inline-flex items-center gap-2 px-6 py-2 rounded-lg bg-gradient-to-r from-purple-600 to-blue-600 text-white font-medium hover:from-purple-700 hover:to-blue-700 transition disabled:opacity-50 disabled:cursor-not-allowed"
            >
              {isDiscovering ? (
                <>
                  <div className="w-4 h-4 border-2 border-white/30 border-t-white rounded-full animate-spin" />
                  Discovering...
                </>
              ) : (
                <>
                  <Search className="w-4 h-4" />
                  Start Discovery →
                </>
              )}
            </button>
          </div>
        </motion.div>
      </div>
    </AnimatePresence>
  );
}

